# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/evan/group55

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/evan/group55

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/evan/group55/CMakeFiles /home/evan/group55//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/evan/group55/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SecuritySystem

# Build rule for target.
SecuritySystem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SecuritySystem
.PHONY : SecuritySystem

# fast build rule for target.
SecuritySystem/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/build
.PHONY : SecuritySystem/fast

Home_Panel.o: Home_Panel.cpp.o
.PHONY : Home_Panel.o

# target to build an object file
Home_Panel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/Home_Panel.cpp.o
.PHONY : Home_Panel.cpp.o

Home_Panel.i: Home_Panel.cpp.i
.PHONY : Home_Panel.i

# target to preprocess a source file
Home_Panel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/Home_Panel.cpp.i
.PHONY : Home_Panel.cpp.i

Home_Panel.s: Home_Panel.cpp.s
.PHONY : Home_Panel.s

# target to generate assembly for a file
Home_Panel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/Home_Panel.cpp.s
.PHONY : Home_Panel.cpp.s

Login_Panel.o: Login_Panel.cpp.o
.PHONY : Login_Panel.o

# target to build an object file
Login_Panel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/Login_Panel.cpp.o
.PHONY : Login_Panel.cpp.o

Login_Panel.i: Login_Panel.cpp.i
.PHONY : Login_Panel.i

# target to preprocess a source file
Login_Panel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/Login_Panel.cpp.i
.PHONY : Login_Panel.cpp.i

Login_Panel.s: Login_Panel.cpp.s
.PHONY : Login_Panel.s

# target to generate assembly for a file
Login_Panel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/Login_Panel.cpp.s
.PHONY : Login_Panel.cpp.s

SecuritySystem.o: SecuritySystem.cpp.o
.PHONY : SecuritySystem.o

# target to build an object file
SecuritySystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/SecuritySystem.cpp.o
.PHONY : SecuritySystem.cpp.o

SecuritySystem.i: SecuritySystem.cpp.i
.PHONY : SecuritySystem.i

# target to preprocess a source file
SecuritySystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/SecuritySystem.cpp.i
.PHONY : SecuritySystem.cpp.i

SecuritySystem.s: SecuritySystem.cpp.s
.PHONY : SecuritySystem.s

# target to generate assembly for a file
SecuritySystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/SecuritySystem.cpp.s
.PHONY : SecuritySystem.cpp.s

UI.o: UI.cpp.o
.PHONY : UI.o

# target to build an object file
UI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/UI.cpp.o
.PHONY : UI.cpp.o

UI.i: UI.cpp.i
.PHONY : UI.i

# target to preprocess a source file
UI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/UI.cpp.i
.PHONY : UI.cpp.i

UI.s: UI.cpp.s
.PHONY : UI.s

# target to generate assembly for a file
UI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/UI.cpp.s
.PHONY : UI.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SecuritySystem"
	@echo "... Home_Panel.o"
	@echo "... Home_Panel.i"
	@echo "... Home_Panel.s"
	@echo "... Login_Panel.o"
	@echo "... Login_Panel.i"
	@echo "... Login_Panel.s"
	@echo "... SecuritySystem.o"
	@echo "... SecuritySystem.i"
	@echo "... SecuritySystem.s"
	@echo "... UI.o"
	@echo "... UI.i"
	@echo "... UI.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

