# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/evan/Downloads/clion-2025.3.2/bin/cmake/linux/x64/bin/cmake

# The command to remove a file.
RM = /home/evan/Downloads/clion-2025.3.2/bin/cmake/linux/x64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/evan/group55

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/evan/group55

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/home/evan/Downloads/clion-2025.3.2/bin/cmake/linux/x64/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/evan/Downloads/clion-2025.3.2/bin/cmake/linux/x64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/evan/Downloads/clion-2025.3.2/bin/cmake/linux/x64/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/evan/Downloads/clion-2025.3.2/bin/cmake/linux/x64/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/evan/Downloads/clion-2025.3.2/bin/cmake/linux/x64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/evan/Downloads/clion-2025.3.2/bin/cmake/linux/x64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/evan/Downloads/clion-2025.3.2/bin/cmake/linux/x64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/evan/Downloads/clion-2025.3.2/bin/cmake/linux/x64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/evan/group55/CMakeFiles /home/evan/group55//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/evan/group55/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SecuritySystem

# Build rule for target.
SecuritySystem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SecuritySystem
.PHONY : SecuritySystem

# fast build rule for target.
SecuritySystem/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/build
.PHONY : SecuritySystem/fast

#=============================================================================
# Target rules for targets named StorageTests

# Build rule for target.
StorageTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 StorageTests
.PHONY : StorageTests

# fast build rule for target.
StorageTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StorageTests.dir/build.make CMakeFiles/StorageTests.dir/build
.PHONY : StorageTests/fast

#=============================================================================
# Target rules for targets named ImageTests

# Build rule for target.
ImageTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ImageTests
.PHONY : ImageTests

# fast build rule for target.
ImageTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageTests.dir/build.make CMakeFiles/ImageTests.dir/build
.PHONY : ImageTests/fast

#=============================================================================
# Target rules for targets named FileTests

# Build rule for target.
FileTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FileTests
.PHONY : FileTests

# fast build rule for target.
FileTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileTests.dir/build.make CMakeFiles/FileTests.dir/build
.PHONY : FileTests/fast

#=============================================================================
# Target rules for targets named VideoTests

# Build rule for target.
VideoTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VideoTests
.PHONY : VideoTests

# fast build rule for target.
VideoTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VideoTests.dir/build.make CMakeFiles/VideoTests.dir/build
.PHONY : VideoTests/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

Config_Panel.o: Config_Panel.cpp.o
.PHONY : Config_Panel.o

# target to build an object file
Config_Panel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/Config_Panel.cpp.o
.PHONY : Config_Panel.cpp.o

Config_Panel.i: Config_Panel.cpp.i
.PHONY : Config_Panel.i

# target to preprocess a source file
Config_Panel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/Config_Panel.cpp.i
.PHONY : Config_Panel.cpp.i

Config_Panel.s: Config_Panel.cpp.s
.PHONY : Config_Panel.s

# target to generate assembly for a file
Config_Panel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/Config_Panel.cpp.s
.PHONY : Config_Panel.cpp.s

File.o: File.cpp.o
.PHONY : File.o

# target to build an object file
File.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/File.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StorageTests.dir/build.make CMakeFiles/StorageTests.dir/File.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageTests.dir/build.make CMakeFiles/ImageTests.dir/File.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileTests.dir/build.make CMakeFiles/FileTests.dir/File.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VideoTests.dir/build.make CMakeFiles/VideoTests.dir/File.cpp.o
.PHONY : File.cpp.o

File.i: File.cpp.i
.PHONY : File.i

# target to preprocess a source file
File.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/File.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StorageTests.dir/build.make CMakeFiles/StorageTests.dir/File.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageTests.dir/build.make CMakeFiles/ImageTests.dir/File.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileTests.dir/build.make CMakeFiles/FileTests.dir/File.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VideoTests.dir/build.make CMakeFiles/VideoTests.dir/File.cpp.i
.PHONY : File.cpp.i

File.s: File.cpp.s
.PHONY : File.s

# target to generate assembly for a file
File.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/File.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StorageTests.dir/build.make CMakeFiles/StorageTests.dir/File.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageTests.dir/build.make CMakeFiles/ImageTests.dir/File.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileTests.dir/build.make CMakeFiles/FileTests.dir/File.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VideoTests.dir/build.make CMakeFiles/VideoTests.dir/File.cpp.s
.PHONY : File.cpp.s

FileTests.o: FileTests.cpp.o
.PHONY : FileTests.o

# target to build an object file
FileTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileTests.dir/build.make CMakeFiles/FileTests.dir/FileTests.cpp.o
.PHONY : FileTests.cpp.o

FileTests.i: FileTests.cpp.i
.PHONY : FileTests.i

# target to preprocess a source file
FileTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileTests.dir/build.make CMakeFiles/FileTests.dir/FileTests.cpp.i
.PHONY : FileTests.cpp.i

FileTests.s: FileTests.cpp.s
.PHONY : FileTests.s

# target to generate assembly for a file
FileTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileTests.dir/build.make CMakeFiles/FileTests.dir/FileTests.cpp.s
.PHONY : FileTests.cpp.s

Home_Panel.o: Home_Panel.cpp.o
.PHONY : Home_Panel.o

# target to build an object file
Home_Panel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/Home_Panel.cpp.o
.PHONY : Home_Panel.cpp.o

Home_Panel.i: Home_Panel.cpp.i
.PHONY : Home_Panel.i

# target to preprocess a source file
Home_Panel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/Home_Panel.cpp.i
.PHONY : Home_Panel.cpp.i

Home_Panel.s: Home_Panel.cpp.s
.PHONY : Home_Panel.s

# target to generate assembly for a file
Home_Panel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/Home_Panel.cpp.s
.PHONY : Home_Panel.cpp.s

Image.o: Image.cpp.o
.PHONY : Image.o

# target to build an object file
Image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/Image.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StorageTests.dir/build.make CMakeFiles/StorageTests.dir/Image.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageTests.dir/build.make CMakeFiles/ImageTests.dir/Image.cpp.o
.PHONY : Image.cpp.o

Image.i: Image.cpp.i
.PHONY : Image.i

# target to preprocess a source file
Image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/Image.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StorageTests.dir/build.make CMakeFiles/StorageTests.dir/Image.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageTests.dir/build.make CMakeFiles/ImageTests.dir/Image.cpp.i
.PHONY : Image.cpp.i

Image.s: Image.cpp.s
.PHONY : Image.s

# target to generate assembly for a file
Image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/Image.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StorageTests.dir/build.make CMakeFiles/StorageTests.dir/Image.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageTests.dir/build.make CMakeFiles/ImageTests.dir/Image.cpp.s
.PHONY : Image.cpp.s

ImageTests.o: ImageTests.cpp.o
.PHONY : ImageTests.o

# target to build an object file
ImageTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageTests.dir/build.make CMakeFiles/ImageTests.dir/ImageTests.cpp.o
.PHONY : ImageTests.cpp.o

ImageTests.i: ImageTests.cpp.i
.PHONY : ImageTests.i

# target to preprocess a source file
ImageTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageTests.dir/build.make CMakeFiles/ImageTests.dir/ImageTests.cpp.i
.PHONY : ImageTests.cpp.i

ImageTests.s: ImageTests.cpp.s
.PHONY : ImageTests.s

# target to generate assembly for a file
ImageTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageTests.dir/build.make CMakeFiles/ImageTests.dir/ImageTests.cpp.s
.PHONY : ImageTests.cpp.s

Login_Panel.o: Login_Panel.cpp.o
.PHONY : Login_Panel.o

# target to build an object file
Login_Panel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/Login_Panel.cpp.o
.PHONY : Login_Panel.cpp.o

Login_Panel.i: Login_Panel.cpp.i
.PHONY : Login_Panel.i

# target to preprocess a source file
Login_Panel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/Login_Panel.cpp.i
.PHONY : Login_Panel.cpp.i

Login_Panel.s: Login_Panel.cpp.s
.PHONY : Login_Panel.s

# target to generate assembly for a file
Login_Panel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/Login_Panel.cpp.s
.PHONY : Login_Panel.cpp.s

SecuritySystem.o: SecuritySystem.cpp.o
.PHONY : SecuritySystem.o

# target to build an object file
SecuritySystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/SecuritySystem.cpp.o
.PHONY : SecuritySystem.cpp.o

SecuritySystem.i: SecuritySystem.cpp.i
.PHONY : SecuritySystem.i

# target to preprocess a source file
SecuritySystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/SecuritySystem.cpp.i
.PHONY : SecuritySystem.cpp.i

SecuritySystem.s: SecuritySystem.cpp.s
.PHONY : SecuritySystem.s

# target to generate assembly for a file
SecuritySystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/SecuritySystem.cpp.s
.PHONY : SecuritySystem.cpp.s

Storage.o: Storage.cpp.o
.PHONY : Storage.o

# target to build an object file
Storage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/Storage.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StorageTests.dir/build.make CMakeFiles/StorageTests.dir/Storage.cpp.o
.PHONY : Storage.cpp.o

Storage.i: Storage.cpp.i
.PHONY : Storage.i

# target to preprocess a source file
Storage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/Storage.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StorageTests.dir/build.make CMakeFiles/StorageTests.dir/Storage.cpp.i
.PHONY : Storage.cpp.i

Storage.s: Storage.cpp.s
.PHONY : Storage.s

# target to generate assembly for a file
Storage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/Storage.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StorageTests.dir/build.make CMakeFiles/StorageTests.dir/Storage.cpp.s
.PHONY : Storage.cpp.s

StorageTests.o: StorageTests.cpp.o
.PHONY : StorageTests.o

# target to build an object file
StorageTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StorageTests.dir/build.make CMakeFiles/StorageTests.dir/StorageTests.cpp.o
.PHONY : StorageTests.cpp.o

StorageTests.i: StorageTests.cpp.i
.PHONY : StorageTests.i

# target to preprocess a source file
StorageTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StorageTests.dir/build.make CMakeFiles/StorageTests.dir/StorageTests.cpp.i
.PHONY : StorageTests.cpp.i

StorageTests.s: StorageTests.cpp.s
.PHONY : StorageTests.s

# target to generate assembly for a file
StorageTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StorageTests.dir/build.make CMakeFiles/StorageTests.dir/StorageTests.cpp.s
.PHONY : StorageTests.cpp.s

Storage_Panel.o: Storage_Panel.cpp.o
.PHONY : Storage_Panel.o

# target to build an object file
Storage_Panel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/Storage_Panel.cpp.o
.PHONY : Storage_Panel.cpp.o

Storage_Panel.i: Storage_Panel.cpp.i
.PHONY : Storage_Panel.i

# target to preprocess a source file
Storage_Panel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/Storage_Panel.cpp.i
.PHONY : Storage_Panel.cpp.i

Storage_Panel.s: Storage_Panel.cpp.s
.PHONY : Storage_Panel.s

# target to generate assembly for a file
Storage_Panel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/Storage_Panel.cpp.s
.PHONY : Storage_Panel.cpp.s

UI.o: UI.cpp.o
.PHONY : UI.o

# target to build an object file
UI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/UI.cpp.o
.PHONY : UI.cpp.o

UI.i: UI.cpp.i
.PHONY : UI.i

# target to preprocess a source file
UI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/UI.cpp.i
.PHONY : UI.cpp.i

UI.s: UI.cpp.s
.PHONY : UI.s

# target to generate assembly for a file
UI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/UI.cpp.s
.PHONY : UI.cpp.s

Video.o: Video.cpp.o
.PHONY : Video.o

# target to build an object file
Video.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VideoTests.dir/build.make CMakeFiles/VideoTests.dir/Video.cpp.o
.PHONY : Video.cpp.o

Video.i: Video.cpp.i
.PHONY : Video.i

# target to preprocess a source file
Video.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VideoTests.dir/build.make CMakeFiles/VideoTests.dir/Video.cpp.i
.PHONY : Video.cpp.i

Video.s: Video.cpp.s
.PHONY : Video.s

# target to generate assembly for a file
Video.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VideoTests.dir/build.make CMakeFiles/VideoTests.dir/Video.cpp.s
.PHONY : Video.cpp.s

VideoTests.o: VideoTests.cpp.o
.PHONY : VideoTests.o

# target to build an object file
VideoTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VideoTests.dir/build.make CMakeFiles/VideoTests.dir/VideoTests.cpp.o
.PHONY : VideoTests.cpp.o

VideoTests.i: VideoTests.cpp.i
.PHONY : VideoTests.i

# target to preprocess a source file
VideoTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VideoTests.dir/build.make CMakeFiles/VideoTests.dir/VideoTests.cpp.i
.PHONY : VideoTests.cpp.i

VideoTests.s: VideoTests.cpp.s
.PHONY : VideoTests.s

# target to generate assembly for a file
VideoTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VideoTests.dir/build.make CMakeFiles/VideoTests.dir/VideoTests.cpp.s
.PHONY : VideoTests.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecuritySystem.dir/build.make CMakeFiles/SecuritySystem.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... FileTests"
	@echo "... ImageTests"
	@echo "... SecuritySystem"
	@echo "... StorageTests"
	@echo "... VideoTests"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... Config_Panel.o"
	@echo "... Config_Panel.i"
	@echo "... Config_Panel.s"
	@echo "... File.o"
	@echo "... File.i"
	@echo "... File.s"
	@echo "... FileTests.o"
	@echo "... FileTests.i"
	@echo "... FileTests.s"
	@echo "... Home_Panel.o"
	@echo "... Home_Panel.i"
	@echo "... Home_Panel.s"
	@echo "... Image.o"
	@echo "... Image.i"
	@echo "... Image.s"
	@echo "... ImageTests.o"
	@echo "... ImageTests.i"
	@echo "... ImageTests.s"
	@echo "... Login_Panel.o"
	@echo "... Login_Panel.i"
	@echo "... Login_Panel.s"
	@echo "... SecuritySystem.o"
	@echo "... SecuritySystem.i"
	@echo "... SecuritySystem.s"
	@echo "... Storage.o"
	@echo "... Storage.i"
	@echo "... Storage.s"
	@echo "... StorageTests.o"
	@echo "... StorageTests.i"
	@echo "... StorageTests.s"
	@echo "... Storage_Panel.o"
	@echo "... Storage_Panel.i"
	@echo "... Storage_Panel.s"
	@echo "... UI.o"
	@echo "... UI.i"
	@echo "... UI.s"
	@echo "... Video.o"
	@echo "... Video.i"
	@echo "... Video.s"
	@echo "... VideoTests.o"
	@echo "... VideoTests.i"
	@echo "... VideoTests.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

